apiVersion: v1
kind: Secret
metadata:
  name: app-secret
type: Opaque
stringData:
  # stringData lets you write plain text; Kubernetes will Base64-encode it automatically!
  DB_PASSWORD: "SuperSecretPassword#2026!"
  STRIPE_API_KEY: "sk_live_987654321_secret"
  
  # Sensitive configuration file
  api-credentials.json: |
    {
      "apiKey": "stripe_live_key_abc123",
      "secretToken": "top_secret_token_xyz987"
    }
